import assert from 'node:assert/strict';
import {cardPoints,comboReward,burnReward,scorePlay} from './dist/scoring.js';
import {deal,play} from './dist/engine.js';
const c=(r,s=0)=>({r,s,id:`${r}-${s}`});
assert.deepEqual([3,4,5,6,7,11,12,13,14].map(r=>cardPoints(c(r))),[30,40,50,60,70,110,120,130,150]);
assert.deepEqual([2,8,9,10].map(r=>cardPoints(c(r))),[200,240,260,300]);
assert.equal(scorePlay([c(3),c(4),c(5)]).points,240);
assert.equal(scorePlay([c(6),c(6,1),c(6,2)]).points,450);
assert.equal(comboReward([c(6),c(6,1),c(6,2)],true).mult,3);
assert.equal(comboReward([c(3),c(3,1)],true).mult,1.75);
const kings=Array.from({length:4},(_,i)=>c(13,i));
assert.equal(scorePlay(kings).points,2080);
assert.equal(scorePlay(kings,{burnedCards:kings}).points,2310);
assert.equal(scorePlay([c(10)],{burnedCards:[c(10)]}).points,475);
for(const [n,mult] of [[4,1],[5,1.25],[9,1.25],[10,1.5],[15,1.75],[20,2],[52,2]])assert.equal(burnReward(Array.from({length:n},()=>c(7))).mult,mult);
assert.ok(burnReward([c(13),c(10)]).points>burnReward([c(3),c(10)]).points);
assert.equal(burnReward([c(13),c(10)],true).points-burnReward([c(13),c(10)]).points,70);
let g=deal();g.pile=[c(4),c(5)];g.player.hand=[c(10)];const before=[...g.pile,...g.player.hand],result=play(g,'player',['10-0']);assert.deepEqual(result.burnedCards,before);assert.deepEqual(g.pile,[]);const award=scorePlay(result.cards,{burnedCards:result.burnedCards,speedBonus:40});assert.equal(award.points,538);assert.deepEqual(JSON.parse(JSON.stringify(award)),award);
g=deal();g.pile=[c(14)];g.player.hand=[c(3)];g.player.face=[];g.deck=[];g.player.hand=[];g.player.blind=[c(3)];assert.ok(play(g,'player',['3-0']).pickup);
assert.equal(burnReward([]).points,0);
console.log('Rank scoring checks passed: ranks, magic premiums, combos, burn value and tiers, perk arithmetic, engine burn snapshot and saved receipts.');
